---
- name: Install XQuartz
  homebrew_cask:
    name: xquartz
    state: present

- name: Install required tools
  homebrew:
    name:
      # These are useful when building python distributions locally
      - tcl-tk
      - openssl
      - readline
      - sqlite3 
      - xz
      - zlib