---
- name: Insall Homebrew + required libraries
  ansible.builtin.include_role:
    name: geerlingguy.mac.homebrew
  vars:
    homebrew_installed_packages:
      - libomp
      - tcl-tk
# This is overwritten by our group_vars (cpp.build-machines)
