---
- name: Install Homebrew + required libraries
  ansible.builtin.include_role:
    name: geerlingguy.mac.homebrew
  vars:
    homebrew_installed_packages:
      - libomp
      - tcl-tk
      - openssl@1.1
  when: not cpp_buildmachine
# This is overwritten by our group_vars (cpp.build-machines)
