---
- name: Install system development libraries (RedHat)
  ansible.builtin.dnf:
    name:
      - dbus-devel # Qt build dependency
      - gd-devel # for graphviz
      - libcap-devel # Qt build dependency
      - libdrm-devel # Qt build dependency
      - libffi-devel
      - libjpeg-turbo-devel
      - libX11-devel
      - libxcb-devel # Qt build dependency
      - libXcomposite-devel # Qt build dependency
      - libXcursor-devel # Qt build dependency
      - libXext-devel # Qt build dependency
      - libXfixes-devel # Qt build dependency
      - libXi-devel # Qt build dependency
      - libxkbcommon-x11 # Qt build dependency
      - libxkbfile # Qt build dependency
      - libXmu-devel
      - libXrandr-devel # Qt build dependency
      - libXrender-devel # Qt build dependency
      - libXScrnSaver-devel # Qt build dependency
      - libXtst-devel # Qt build dependency
      - mesa-libEGL-devel # Qt build dependency
      - mesa-libGL-devel # Qt build dependency
      - mesa-libGLU-devel # Qt build dependency
      - ncurses-devel # To build clewn
      - pango-devel # for graphviz
      - readline-devel # To build clewn
      - tcl-devel
      - tk-devel
      - unixODBC
      - urw-fonts
      - xcb-util # Qt build dependency
      - xcb-util-cursor # Qt build dependency
      - xcb-util-image # Qt build dependency
      - xcb-util-keysyms # Qt build dependency
      - xcb-util-renderutil # Qt build dependency
      - xcb-util-wm # Qt build dependency
      - alsa-lib-devel # QtWebEngine dependency
      - cups # Qt PrintSupport dependency
      - cups-devel # Qt PrintSupport dependency
    state: present
    enable_plugin: crb
  become: true
